variables:
  - name: terraformVersion
    value: 1.0.0
  - name: serviceConnectionName
    value: MSDN
  - name: backendAzureRmResourceGroupName
    value: tfstate-rg
  - name: backendAzureRmStorageAccountName
    value: chterraformbestpractices
  - name: domainName
    value: psug.local
  - name: domainAdmin
    value: psug\azureuser
  - name: automationAccountName
    value: psugDSC
  - name: automationAccountRGName
    value: psug-aadsc
  - name: VNetRGName
    value: psug-vnet
  - name: VMRGName
    value: psug-vms
  - name: NSGRGName
    value: psug-nsg
  - name: DSCSAName
    value: psugdscstorage01
  - name: DSCSARGName
    value: psugsa-rg
