variables:
  - name: terraformVersion
    value: 1.0.0
  - name: serviceConnectionName
    value: MSDN
  - name: backendAzureRmResourceGroupName
    value: tfstate-rg
  - name: backendAzureRmStorageAccountName
    value: chterraformbestpractices
  - name: domainName
    value: psug.local
  - name: domainAdmin
    value: psug\azureuser
  - name: automationAccountName
    value: psugDSC
  - name: automationAccountRGName
    value: UserGroup-rg
