# specific path build
trigger:
  paths:
    include:
      - PowerShellUserGroup-2020-07-08/DSC/DSCConfigurations
      - PowerShellUserGroup-2020-07-08/Pipelines/dscmodules.yml

stages:
  - stage: Build
    jobs:
      - job: Build
        variables:
          - template: variables/prod/prod_vars.yml

        pool:
          vmImage: "windows-latest"

        steps:
          - task: PowerShell@2
            inputs:
              targetType: "filepath"
              filePath: "$(Build.SourcesDirectory)/PowerShellUserGroup-2020-07-08/DSC/NeededModules.ps1"
              pwsh: false
            displayName: Install Needed Modules

          - task: PowerShell@2
            inputs:
              targetType: "filepath"
              filePath: "$(Build.SourcesDirectory)/PowerShellUserGroup-2020-07-08/DSC/DSCConfigurations/CreateNewADForest/Config.ps1"
              pwsh: false
              arguments: >
                -OutputPath "$(Build.ArtifactStagingDirectory)"
                -SafeModepwd "$env:SafeModePwd"
                -DomainAdmin "${{variables.domainAdmin}}"
                -DomainAdminPwd "$env:DomainAdminPwd"
                -DomainName "${{variables.domainName}}"
                -ConfigPath "$(Build.SourcesDirectory)/PowerShellUserGroup-2020-07-08/DSC/DSCConfigurations/CreateNewADForest/Config.psd1"
            env:
              DomainAdminPwd: $(DomainAdminPwd)
              SafeModePwd: $(SafeModepwd)
            displayName: Compile CreateNewADForest

          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: >
                Rename-Item -Path "$(Build.ArtifactStagingDirectory)\localhost.mof" -NewName 'CreateNewADForest.mof'
            displayName: Rename file CreateNewADForest.mof

          - task: PowerShell@2
            inputs:
              targetType: "filepath"
              filePath: "$(Build.SourcesDirectory)/PowerShellUserGroup-2020-07-08/DSC/DSCConfigurations/AddDCToExistingForest/Config.ps1"
              pwsh: false
              arguments: >
                -OutputPath "$(Build.ArtifactStagingDirectory)"
                -SafeModepwd "$env:SafeModePwd"
                -DomainAdmin "$(domainAdmin)"
                -DomainAdminPwd "$env:DomainAdminPwd"
                -DomainName "$(domainName)"
                -ConfigPath "$(Build.SourcesDirectory)/PowerShellUserGroup-2020-07-08/DSC/DSCConfigurations/AddDCToExistingForest/Config.psd1"
            env:
              DomainAdminPwd: $(DomainAdminPwd)
              SafeModePwd: $(SafeModepwd)
            displayName: Compile AddDCToExistingForest

          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: >
                Rename-Item -Path "$(Build.ArtifactStagingDirectory)\localhost.mof" -NewName 'AddDCToExistingForest.mof'
            displayName: Rename file CreateNewADForest.mof

          - task: PowerShell@2
            inputs:
              targetType: "filepath"
              filePath: "$(Build.SourcesDirectory)/PowerShellUserGroup-2020-07-08/DSC/DSCConfigurations/CreateFile/Config.ps1"
              pwsh: false
              arguments: >
                -OutputPath "$(Build.ArtifactStagingDirectory)"
            env:
              DomainAdminPwd: $(DomainAdminPwd)
              SafeModePwd: $(SafeModepwd)
            displayName: Compile CreateFile

          - task: PowerShell@2
            inputs:
              targetType: "inline"
              script: >
                Rename-Item -Path "$(Build.ArtifactStagingDirectory)\localhost.mof" -NewName 'CreateFile.mof'
            displayName: Rename file CreateFile.mof

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "mof"
              publishLocation: "Container"
            displayName: "Create Artifact for all mof files"

  - stage: PublishToAzureAutomationDSC
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: Deploy
        variables:
          - template: variables/prod/prod_vars.yml

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "mof"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download mof global artifact"

          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "MSDN"
              ScriptType: "InlineScript"
              Inline: >
                $DSCModules = New-Object -TypeName 'System.Collections.Generic.List[System.Object]'

                $row1 = [PSCustomObject]@{
                  Name = "ActiveDirectoryDSC"
                  Version = "6.0.1"
                }

                $row2 = [PSCustomObject]@{
                  Name = "ComputerManagementDSC"
                  Version = "8.4.0"
                }

                $row3 = [PSCustomObject]@{
                  Name = "StorageDSC"
                  Version = "5.0.1"
                }

                $row4 = [PSCustomObject]@{
                  Name = "xPSDesiredStateConfiguration"
                  Version = "9.0.1"
                }

                $DSCModules.Add($row1)
                $DSCModules.Add($row2)
                $DSCModules.Add($row3)
                $DSCModules.Add($row4)

                foreach($module in $DSCModules)
                {
                  if(-not(Get-AzAutomationModule -AutomationAccountName $(automationAccountName) -Name $module -ResourceGroupName $(automationAccountRGName)))
                  {
                      $splat = @{
                        AutomationAccountName = $(automationAccountName)
                        ResourceGroupName     = $(automationAccountRGName)
                        Name                  = $module.Name
                        ContentLinkUri        = "https://www.powershellgallery.com/api/v2/package/$($module.Name)/$($module.Version)"
                      }

                      New-AzAutomationModule @splat
                  }
                }
              azurePowerShellVersion: "LatestVersion"
              pwsh: true
            displayName: "Add the needed DSC Modules to Azure Automation DSC"
#          - task: AzurePowerShell@5
#            inputs:
#              azureSubscription: "MSDN"
#              ScriptType: "InlineScript"
#              Inline: >
#                foreach($mof in (Get-Childitem -Path $(System.DefaultWorkingDirectory)))
#                {
#
#                }
#              azurePowerShellVersion: "LatestVersion"
#              pwsh: true
#            displayName: "Add Mofs to Azure Automation DSC"
