# specific path build
trigger:
  paths:
    include:
      - PowerShellUserGroup-2020-07-08/DSC/DSCConfigurations
      - PowerShellUserGroup-2020-07-08/Pipelines/dscmodules.yml

variables:
  - name: domainName
    value: psug.local
  - name: domainAdmin
    value: psug\azureuser

stages:
  - stage: Build
    jobs:
      - job: Build

        pool:
          vmImage: "windows-latest"

        steps:
          - task: PowerShell@2
            inputs:
              targetType: "filepath"
              filePath: "$(Build.SourcesDirectory)/PowerShellUserGroup-2020-07-08/DSC/NeededModules.ps1"
              pwsh: false
            displayName: Install Needed Modules

          - task: PowerShell@2
            inputs:
              targetType: "filepath"
              filePath: "$(Build.SourcesDirectory)/PowerShellUserGroup-2020-07-08/DSC/DSCConfigurations/CreateNewADForest/Config.ps1"
              pwsh: false
              arguments: >
                "-OutputPath "$(Build.ArtifactStagingDirectory)""
                "-SafeModepwd $env:SafeModePwd"
                "-DomainAdmin $(domainAdmin)"
                "-DomainAdminPwd $env:DomainAdminPwd"
                "-DomainName $(domainName)"
            env:
              DomainAdminPwd: $(DomainAdminPwd)
              SafeModePwd: $(SafeModepwd)
            displayName: Compile CreateNewADForest
#          - task: PublishBuildArtifacts@1
#            inputs:
#              PathtoPublish: "$(Build.SourcesDirectory)/Terraform/services"
#              ArtifactName: "creaton"
#              publishLocation: "Container"
#            displayName: "Create Artifact for all creaton services"
#
#  - stage: AzureAutomationAccount
#    dependsOn: Build
#    condition: succeeded()
#
#    jobs:
#      - job: Deploy
#        variables:
#          - template: variables/prod/prod_vars.yml
#
#        pool:
#          vmImage: "ubuntu-latest"
#
#        steps:
#          - task: DownloadBuildArtifacts@0
#            inputs:
#              buildType: "current"
#              downloadType: "single"
#              artifactName: "global"
#              downloadPath: "$(System.DefaultWorkingDirectory)"
#            displayName: "Download Azure global artifact"
#
#          - task: DownloadBuildArtifacts@0
#            inputs:
#              buildType: "current"
#              downloadType: "single"
#              artifactName: "creaton"
#              downloadPath: "$(System.DefaultWorkingDirectory)"
#            displayName: "Download creaton artifact"
#
#          - template: templates/terraform.yml
#            parameters:
#              terraformVersion: "${{variables.terraformVersion}}"
#              serviceConnectionName: "${{variables.serviceConnectionName}}"
#              backendAzureRmResourceGroupName: "${{variables.backendAzureRmResourceGroupName}}"
#              backendAzureRmStorageAccountName: "${{variables.backendAzureRmStorageAccountName}}"
#              backendAzureRmContainerName: "managementgovernance"
#              backendAzureRmKey: "allowedlocations.tfstate"
#              workingDirectory: "$(System.DefaultWorkingDirectory)/creaton/policy/allowedlocations"
#              description: "Allowed Locations"
