# specific path build
trigger:
  paths:
    include:
      - DSCCommunityCall/Terraform/*
      - DSCCommunityCall/Pipelines/mainpipeline.yml

stages:
  - stage: Build
    jobs:
      - job: Build

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/DSCCommunityCall/Terraform/global"
              ArtifactName: "global"
              publishLocation: "Container"
            displayName: "Create Artifact for the global folder"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/DSCCommunityCall/Terraform/services"
              ArtifactName: "DSCCommunityCall"
              publishLocation: "Container"
            displayName: "Create Artifact for all DSCCommunityCall services"

  - stage: AzureAutomationAccount
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: Deploy
        variables:
          - template: variables/prod/prod_vars.yml

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "global"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download Azure global artifact"

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "DSCCommunityCall"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download DSCCommunityCall artifact"

          - template: templates/terraform.yml
            parameters:
              terraformVersion: "${{variables.terraformVersion}}"
              serviceConnectionName: "${{variables.serviceConnectionName}}"
              backendAzureRmResourceGroupName: "${{variables.backendAzureRmResourceGroupName}}"
              backendAzureRmStorageAccountName: "${{variables.backendAzureRmStorageAccountName}}"
              backendAzureRmContainerName: "psug-aadsc"
              backendAzureRmKey: "psug.tfstate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/DSCCommunityCall/automationaccount"
              description: "DSCCommunityCall automation account"
              planparameters: "-var automation_account_name=${{variables.automationAccountName}} -var rg_name=${{variables.automationAccountRGName}}"

  - stage: VNET
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: Deploy
        variables:
          - template: variables/prod/prod_vars.yml

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "global"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download Azure global artifact"

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "DSCCommunityCall"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download DSCCommunityCall artifact"

          - template: templates/terraform.yml
            parameters:
              terraformVersion: "${{variables.terraformVersion}}"
              serviceConnectionName: "${{variables.serviceConnectionName}}"
              backendAzureRmResourceGroupName: "${{variables.backendAzureRmResourceGroupName}}"
              backendAzureRmStorageAccountName: "${{variables.backendAzureRmStorageAccountName}}"
              backendAzureRmContainerName: "psug-vnet"
              backendAzureRmKey: "psug.tfstate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/DSCCommunityCall/vnet"
              description: "DSCCommunityCall VNET account"
              planparameters: "-var rg_name=${{variables.VNetRGName}}"

  - stage: NSG
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: Deploy
        variables:
          - template: variables/prod/prod_vars.yml

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "global"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download Azure global artifact"

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "DSCCommunityCall"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download DSCCommunityCall artifact"

          - template: templates/terraform.yml
            parameters:
              terraformVersion: "${{variables.terraformVersion}}"
              serviceConnectionName: "${{variables.serviceConnectionName}}"
              backendAzureRmResourceGroupName: "${{variables.backendAzureRmResourceGroupName}}"
              backendAzureRmStorageAccountName: "${{variables.backendAzureRmStorageAccountName}}"
              backendAzureRmContainerName: "psug-nsg"
              backendAzureRmKey: "psugnsg.tfstate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/DSCCommunityCall/networksecuritygroup"
              description: "DSCCommunityCall DC"
              planparameters: "-var rg_name=${{variables.NSGRGName}} -var subnet_rg=${{variables.VNetRGName}}"

  - stage: StorageAccounts
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: Deploy
        variables:
          - template: variables/prod/prod_vars.yml

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "global"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download Azure global artifact"

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "DSCCommunityCall"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download DSCCommunityCall artifact"

          - template: templates/terraform.yml
            parameters:
              terraformVersion: "${{variables.terraformVersion}}"
              serviceConnectionName: "${{variables.serviceConnectionName}}"
              backendAzureRmResourceGroupName: "${{variables.backendAzureRmResourceGroupName}}"
              backendAzureRmStorageAccountName: "${{variables.backendAzureRmStorageAccountName}}"
              backendAzureRmContainerName: "psug-sa"
              backendAzureRmKey: "psugdscsa.tfstate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/DSCCommunityCall/storageaccount/dscstrorage"
              description: "DSCCommunityCall SA"
              planparameters: "-var rg_name=${{variables.DSCSARGName}} -var storage_account_name=${{variables.DSCSAName}}"

  - stage: AAVMS
    dependsOn: Build
    condition: succeeded()

    jobs:
      - job: Deploy
        variables:
          - template: variables/prod/prod_vars.yml

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "global"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download Azure global artifact"

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "DSCCommunityCall"
              downloadPath: "$(System.DefaultWorkingDirectory)"
            displayName: "Download DSCCommunityCall artifact"

          - template: templates/terraform.yml
            parameters:
              terraformVersion: "${{variables.terraformVersion}}"
              serviceConnectionName: "${{variables.serviceConnectionName}}"
              backendAzureRmResourceGroupName: "${{variables.backendAzureRmResourceGroupName}}"
              backendAzureRmStorageAccountName: "${{variables.backendAzureRmStorageAccountName}}"
              backendAzureRmContainerName: "psug-vms"
              backendAzureRmKey: "psugdc.tfstate"
              workingDirectory: "$(System.DefaultWorkingDirectory)/DSCCommunityCall/virtualmachines/DC"
              description: "DSCCommunityCall DC"
              planparameters: "-var rg_name=${{variables.VMRGName}} -var subnet_rg=${{variables.VNetRGName}} -var aadsc_rg=${{variables.automationAccountRGName}} -var aadsc_name=${{variables.automationAccountName}}"
